# Test functions

In [1]:
from utils.sparse import *

# Function list 
1. inplace_set_rows_zero_where_sum (X, op, cut)  
2. inplace_set_cols_zero_where_sum (X, op, cut)
3. inplace_set_rows_zero (X, target_rows)
4. inplace_set_cols_zero (X, target_cols)
5. inplace_row_scale (X, scale)
6. inplace_col_scale (X, scale)   
7. sum_cols (X)
8. sum_rows (X)

In [2]:
m = sp.random(4,5,0.5).tocsr()
m.data = np.ones(m.data.shape[0])
print(m.todense())
inplace_row_scale(m,np.array([1,2,3,4]))
print (m.todense())

[[0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0.]]
[[0. 1. 1. 0. 0.]
 [2. 2. 0. 0. 0.]
 [0. 0. 3. 3. 3.]
 [4. 4. 4. 0. 0.]]


In [3]:
m = sp.random(4,5,0.5).tocsc()
m.data = np.ones(m.data.shape[0])
print(m.todense())
inplace_col_scale(m,np.array([1,2,3,4,5]))
print (m.todense())

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 3. 4. 5.]
 [0. 2. 0. 4. 5.]
 [1. 2. 0. 0. 5.]]


In [4]:
m = sp.random(4,5,0.5).tocsr()
m.data = np.ones(m.data.shape[0])
print(m.todense())
inplace_set_rows_zero(m,np.array([1,3]))
print (m.todense())

[[0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [5]:
m = sp.random(4,5,0.5).tocsr()
m.data = np.ones(m.data.shape[0])
print(m.todense())
inplace_set_cols_zero(m,np.array([1,3]))
print (m.todense())

[[0. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 1.]]
[[0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1.]]


In [6]:
m = sp.random(4,5,0.5).tocsr()
print (sum_rows(m))
inplace_set_rows_zero_where_sum(m, '>', 1.5)
print (m.todense())

[2.06284216 0.17633125 0.86179057 1.79197257]
[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.17633125]
 [0.01446204 0.         0.39882688 0.         0.44850165]
 [0.         0.         0.         0.         0.        ]]


In [8]:
m = sp.random(4,5,0.5).tocsr()
print (sum_cols(m))
inplace_set_cols_zero_where_sum(m, '>', 1.5)
print (m.todense())

[1.96108189 1.12923879 0.         1.93997106 0.40970854]
[[0.         0.69020914 0.         0.         0.40970854]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.43902965 0.         0.         0.        ]]
